app:
  mem_limit: 300m
  memswap_limit: 1g
  build: .
  ports:
    - '3000:3000'
  volumes:
    - .:/Users/unbxd/workspace/Docker_apps/Docker-Node
    - /Users/unbxd/workspace/Docker_apps/Docker-Node/app/node_modules